sudo: required
dist: trusty

os: linux

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
    - mysql-server

cache:
  directories:
  - download-cache

env:
  global:
    - LUAJIT_LIB=/usr/lib64/libluajit-5.1.so
    - LUAJIT_INC=/usr/include/luajit-2.0
    - LUA_INCLUDE_DIR=/usr/include/luajit-2.0
    - LUA_CMODULE_DIR=/lib
  matrix:
    - NGINX_VERSION=1.9.15
#    - NGINX_VERSION=1.10.0

services:
 - memcache
 - redis-server

before_install:
  - sudo apt-get install -y axel cpanminus libluajit-5.1-dev libgd-dev

install:
  - if [ ! -d download-cache ]; then mkdir download-cache; fi
  - if [ ! -f download-cache/drizzle7-2011.07.21.tar.gz ]; then wget -O download-cache/drizzle7-2011.07.21.tar.gz http://openresty.org/download/drizzle7-2011.07.21.tar.gz; fi
  - if [ ! -f download-cache/pcre-8.33.tar.gz ]; then wget -O download-cache/pcre-8.33.tar.gz http://ftp.cs.stanford.edu/pub/exim/pcre/pcre-8.33.tar.gz; fi
  - git clone https://github.com/openresty/test-nginx.git
  - git clone https://github.com/openresty/openresty.git ../openresty
  - git clone https://github.com/openresty/no-pool-nginx.git ../no-pool-nginx
  - git clone https://github.com/openresty/nginx-devel-utils.git
  - git clone https://github.com/openresty/mockeagain.git
  - git clone https://github.com/openresty/lua-cjson.git
  - git clone https://github.com/openresty/lua-upstream-nginx-module.git ../lua-upstream-nginx-module
  - git clone https://github.com/openresty/echo-nginx-module.git ../echo-nginx-module
  - git clone https://github.com/openresty/nginx-eval-module.git ../nginx-eval-module
  - git clone https://github.com/simpl/ngx_devel_kit.git ../ndk-nginx-module
  - git clone https://github.com/FRiCKLE/ngx_coolkit.git ../coolkit-nginx-module
  - git clone https://github.com/openresty/headers-more-nginx-module.git ../headers-more-nginx-module
  - git clone https://github.com/openresty/drizzle-nginx-module.git ../drizzle-nginx-module
  - git clone https://github.com/openresty/set-misc-nginx-module.git ../set-misc-nginx-module
  - git clone https://github.com/openresty/memc-nginx-module.git ../memc-nginx-module
  - git clone https://github.com/openresty/rds-json-nginx-module.git ../rds-json-nginx-module
  - git clone https://github.com/openresty/srcache-nginx-module.git ../srcache-nginx-module
  - git clone https://github.com/openresty/redis2-nginx-module.git ../redis2-nginx-module

before_script:
  - mysql -uroot -e 'create database ngx_test; grant all on ngx_test.* to "ngx_test"@"%" identified by "ngx_test"; flush privileges;'

script:
  - tar xzf download-cache/drizzle7-2011.07.21.tar.gz && cd drizzle7-2011.07.21
  - ./configure --prefix=/usr --without-server > build.log 2>&1 || (cat build.log && exit 1)
  - sudo PATH=$PATH make libdrizzle-1.0 install-libdrizzle-1.0 > build.log 2>&1 || (cat build.log && exit 1)
  - cd ..
  - cd mockeagain && make && cd ..
  - cd test-nginx && sudo cpanm . && cd ..
  - cd lua-cjson && make && sudo PATH=$PATH make install && cd ..
  - tar zxf download-cache/pcre-8.33.tar.gz
  - cd pcre-8.33
  - ./configure --prefix=/usr --enable-jit --enable-utf --enable-pcre16 --enable-pcre32 --enable-unicode-properties > build.log 2>&1 || (cat build.log && exit 1)
  - make > build.log 2>&1 || (cat build.log && exit 1)
  - sudo PATH=$PATH make install > build.log 2>&1 || (cat build.log && exit 1)
  - cd ..
  - export PATH=$PATH:`pwd`/nginx-devel-utils
  - sh util/build.sh $NGINX_VERSION > build.log 2>&1 || (cat build.log && exit 1)
  - export PATH=$PATH:`pwd`/work/nginx/sbin
  - export LD_PRELOAD=`pwd`/mockeagain/mockeagain.so
  - export TEST_NGINX_RESOLVER=8.8.4.4
  - dig +short @$TEST_NGINX_RESOLVER openresty.org || exit 0
  - dig +short @$TEST_NGINX_RESOLVER agentzh.org || exit 0
  - prove -r t
